from datetime import datetime
from typing import Dict, Any, List
from ..models.schemas import (
    ChannelProvider,
    SyncPayload,
    ChannelSyncResponse,
    ChannelSyncRequest,
    ChannelSyncResult,
    ClipboardBundle,
    OnboardingPack,
    SolutionPlan
)


def transform_solution_to_sync_payload(solution: SolutionPlan, listing_id: str) -> SyncPayload:
    blocks = {b.section_id: b.content for b in solution.description_blocks}
    
    return SyncPayload(
        listing_id=listing_id,
        title=solution.title_variants[0].title if solution.title_variants else None,
        description=solution.full_compiled_description,
        summary=blocks.get("hook_summary", ""),
        space=blocks.get("the_space", ""),
        access="24/7 Smart lock access. Full private access to entire property.",
        neighborhood=blocks.get("neighborhood", ""),
        notes="Non-smoking indoors. Quiet hours 22:00-08:00.",
        photo_order_ids=[f"photo_pos_{p.position}" for p in solution.photo_strategy]
    )


def build_channel_payload(request: ChannelSyncRequest | SyncPayload, provider: ChannelProvider = ChannelProvider.HOSTAWAY) -> Dict[str, Any]:
    if isinstance(request, ChannelSyncRequest):
        channel = request.channel_type.lower()
        listing_id = request.listing_id
        title = request.selected_title
        description = request.selected_description
    else:
        channel = provider.value
        listing_id = request.listing_id
        title = request.title or ""
        description = request.description or ""
    
    if channel == "hostaway":
        return {
            "listingId": listing_id,
            "name": title,
            "description": description,
            "customFields": {
                "auditOptimized": True,
                "syncSource": "Concierge Audit OS"
            }
        }
    elif channel == "guesty":
        return {
            "_id": listing_id,
            "title": title,
            "publicDescription": {
                "summary": description[:500] if description else "",
                "space": description
            },
            "source": "concierge_audit_os"
        }
    elif channel == "smoobu":
        return {
            "apartmentId": listing_id,
            "name": title,
            "description": description,
            "notice": "Optimized by Concierge Audit OS"
        }
    else:
        return {
            "property_id": listing_id,
            "title": title,
            "description": description,
            "updated_via": "concierge_audit_os_agent"
        }


def sync_to_provider(payload: SyncPayload, provider: ChannelProvider) -> ChannelSyncResponse:
    raw_payload = build_channel_payload(payload, provider)
    updated_fields = [f for f, v in payload.model_dump().items() if v is not None and f != "listing_id"]
    
    return ChannelSyncResponse(
        success=True,
        provider=provider,
        listing_id=payload.listing_id,
        updated_fields=updated_fields,
        raw_response={
            "status": 200,
            "provider_status": "synced",
            "payload_sent": raw_payload
        },
        error_message=None
    )


def dispatch_channel_sync(request: ChannelSyncRequest) -> ChannelSyncResult:
    payload = build_channel_payload(request)
    return ChannelSyncResult(
        success=True,
        audit_id=request.audit_id,
        channel=request.channel_type.upper(),
        listing_id=request.listing_id,
        sync_timestamp=datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
        payload_dispatched=payload,
        message=f"Successfully synchronized {request.channel_type.upper()} listing '{request.listing_id}' with high-converting OTA copy."
    )


def create_clipboard_bundle(solution: SolutionPlan) -> ClipboardBundle:
    captions = [f"Photo #{p.position} ({p.shot_type}): {p.recommended_caption}" for p in solution.photo_strategy]
    
    quick_copy = f"""=== CONCIERGE AUDIT OS: OPTIMIZED LISTING BUNDLE ===
Property: {solution.property_name}

--- [APPROVED TITLE] ---
{solution.title_variants[0].title}

--- [OPTIMIZED 4-BLOCK DESCRIPTION] ---
{solution.full_compiled_description}

--- [HERO PHOTO SEQUENCE & CAPTIONS] ---
""" + "\n".join(captions)

    return ClipboardBundle(
        title=solution.title_variants[0].title,
        description=solution.full_compiled_description,
        captions=[p.recommended_caption for p in solution.photo_strategy],
        quick_copy_all=quick_copy
    )


def create_onboarding_pack(solution: SolutionPlan, audit_data: dict) -> OnboardingPack:
    md_content = f"""# Listing Optimization & Performance Pack
**Property:** {solution.property_name}  
**Generated by:** Concierge Audit OS  
**Status:** {solution.status}  

---

## 1. Selected Title
> **{solution.title_variants[0].title}**  
*Character Count: {solution.title_variants[0].character_count} / Strategy: {solution.title_variants[0].strategy_note}*

---

## 2. Listing Description
{solution.full_compiled_description}

---

## 3. Hero Photo Prioritization Matrix
| Position | Shot Type | Subject & Staging | Caption |
| :--- | :--- | :--- | :--- |
"""
    for photo in solution.photo_strategy:
        md_content += f"| **#{photo.position}** | {photo.shot_type} | {photo.subject} ({photo.staging_notes}) | *\"{photo.recommended_caption}\"* |\n"

    md_content += f"""
---

## 4. Revenue & Yield Strategy
{solution.pricing_strategy_summary}
"""

    return OnboardingPack(
        markdown_content=md_content,
        json_export={
            "solution": solution.model_dump(),
            "audit": audit_data
        }
    )
